$(document).ready(function(){
  $(".icon").click(function(){
    $(".show").toggle();
  });
});
$(document).ready(function(){
  $(".icon2").click(function(){
    $(".show2").toggle();
  });
});
$(document).ready(function(){
  $(".icon3").click(function(){
    $(".show3").toggle();
  });
});
